[package]
name = "defmt-brtt"
version = "0.1.2"
edition = "2021"
rust-version = "1.85"
authors = ["Johannes Cornelis Draajier <jcdra1@gmail.com", "Emil Fresk <emil.fresk@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/datdenkikniet/defmt-brtt"
description = "Defmt logs over RTT as well as through a BBQueue"
keywords = ["defmt", "bbqueue", "rtt", "embedded", "logging"]
categories = ["embedded", "encoding", "no-std", "development-tools"]

[package.metadata.docs.rs]
features = ["async-await"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "1"
critical-section = "1.1"
bbqueue = { version = "0.7", default-features = false, features = ["critical-section"], optional = true }

[features]
default = [
    "rtt",
    "bbq",
]
bbq = [ "dep:bbqueue" ]
async-await = [
    "bbq",
    "bbqueue/maitake-sync-0_3",
]
portable-atomic-critical-section = [ "bbqueue?/portable-atomic-critical-section" ]
rtt = [ ]
